<?php
return array (
  'site_name' => '微信平台',
  'site_title' => '纽曼微信公众服务平台',
  'site_logo' => 'http://car.newsmy.com/image/logo.gif',
  'site_url' => 'http://localhost',
  'site_my' => '纽曼导航',
  'server_key' => 'bc9ed510a91c14331cf2f6ce4169807b',
  'server_topdomain' => 'shop.newsmy.com',
  'connectout' => '用户已到期，请联系管理员或客服充值',
  'ischeckuser' => 'false',
  'reg_needmp' => 'false',
  'open_biz' => '0',
  'isclosekuser' => 'true',
  'server_discuz' => 'http://www.newsmy-car.com/bbs',
  'reg_groupid' => '4',
  'reg_validdays' => '365',
  'router_key' => '2b79c282b0f365ca9782cceb499e6022',
  'ipc' => '京ICP备05055788号-20',
  'site_qq' => '2052977199',
  'site_mp' => '13800000000',
  'site_kfqq' => '2052977199',
  'site_qqqun' => '',
  'site_tel' => '020-88888888',
  'site_adress' => '北京上地',
  'baidu_map_api' => 'KWe2TezxgWBDms0PYjeXBZWt',
  'site_email' => 'admin@newsmy.com',
  'keyword' => '纽曼导航-国内优秀的微信公众智能服务平台，八大微体系：微菜单、微官网、微会员、微活动、微商城、微推送、微服务、微统计，企业微营销必备。',
  'content' => '纽曼导航-国内优秀的微信公众智能服务平台，八大微体系：微菜单、微官网、微会员、微活动、微商城、微推送、微服务、微统计，企业微营销必备。',
  'countsz' => '',
  'copyright' => 'Copyright (c) 2014-2016  纽曼导航 版权所有',
  'ucenter_db_set' => '',
  'ucenter_web_set' => '',
);
?>